### ISSUE TITLE
Could not install bundle

### ISSUE THREAD

**Issue by OskarStark** [kinulab/sonata-gentellela-theme-bundle#4]
```
composer require kinulab/sonata-getellela-theme-bundle
```

error:
<img width="796" alt="bildschirmfoto 2016-09-27 um 11 46 32" src="https://cloud.githubusercontent.com/assets/995707/18868327/135eb0e6-84a8-11e6-926f-34d5f6e098f3.png">

**Comment by nykopol** [comment]
hello @OskarStark, it's just a typo : 

```
composer require kinulab/sonata-ge**n**tellela-theme-bundle
```

Typo aside, this bundle is still young, there is only one version that work with `sonata-project/admin-bundle:^3.8`. If you are looking for an other version of sonata admin let me know and I will do my best to enhance compatibility.
