### ISSUE TITLE
Not Closed "if sonata_admin.adminPool.getOption('search')" 

### ISSUE THREAD

**Issue by vhbmsp** [kinulab/sonata-gentellela-theme-bundle#9]
Replace {% endblock %} with {% endif %}

https://github.com/kinulab/sonata-gentellela-theme-bundle/blob/99f3920bb7b354df4a242f5ba870c237fb3241ab/Resources/views/standard_layout.html.twig#L243

**Comment by nykopol** [comment]
Hi @vhbmsp thanks for your interest in the project. I fixed the bug in the tag ` 3.35.0.1`.
